### PR TITLE
docs: Polish MD template for nicer generated MD file

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
As part of a general docs and DX polish for "getting started", I took a pass at fixing up the template files. This PR removes a lot of the white space from the generated MD file and also polishes some grammar. 

---

### Changes are visible to end-users: no

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
As part of this @alexeagle I also noticed that I think the `{{ if .Computed.javascript -}}` etc values don't work… I tried them with and without the added `-` for whitespace removal, and also tried from the current released `aspect init` command, and the passages I except to see don't show.

But before I create an issue, I wanted to check if I hadn't misunderstood something.

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
The syntax with whitespace is so finicky, I gave up on making the go templates perfect. Instead, for BUILD and bzl files, we just format them after the template engine finishes, see https://github.com/aspect-build/aspect-workflows-template/blob/main/hooks/post_scaffold

So it's probably better just to run mdfmt in that hook and continue to allow sloppiness with the Go template whitespace handling

**Comment by ChrisChinchilla** [comment]
@alexeagle OK, but what about the template variables that don't seem to be working? That seems more important as it means instructions aren't making it to the generated file.

And this PR did fix the whitespace issues as far as I could see as when I tested the `init` command it was full of line after line of whtespace, but I will also look at the hook as I move through things

**Comment by alexeagle** [comment]
I'm sorry, I don't have time to debug the testing setup with you. I'm confident that the templating is working based on running `aspect init` and only the languages I choose end up in the generated README. And yes the whitespace looks better now - it's just difficult for us to keep it this way as we make more edits to the template.

**Pull request merged**
